# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/sikhu/Documents/School/ALX/0/C_Structures

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/sikhu/Documents/School/ALX/0/C_Structures

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/sikhu/Documents/School/ALX/0/C_Structures/CMakeFiles /mnt/c/Users/sikhu/Documents/School/ALX/0/C_Structures//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/sikhu/Documents/School/ALX/0/C_Structures/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named C_Structures

# Build rule for target.
C_Structures: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 C_Structures
.PHONY : C_Structures

# fast build rule for target.
C_Structures/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C_Structures.dir/build.make CMakeFiles/C_Structures.dir/build
.PHONY : C_Structures/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/build
.PHONY : tests/fast

src/data/CSVHandler.o: src/data/CSVHandler.cpp.o
.PHONY : src/data/CSVHandler.o

# target to build an object file
src/data/CSVHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C_Structures.dir/build.make CMakeFiles/C_Structures.dir/src/data/CSVHandler.cpp.o
.PHONY : src/data/CSVHandler.cpp.o

src/data/CSVHandler.i: src/data/CSVHandler.cpp.i
.PHONY : src/data/CSVHandler.i

# target to preprocess a source file
src/data/CSVHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C_Structures.dir/build.make CMakeFiles/C_Structures.dir/src/data/CSVHandler.cpp.i
.PHONY : src/data/CSVHandler.cpp.i

src/data/CSVHandler.s: src/data/CSVHandler.cpp.s
.PHONY : src/data/CSVHandler.s

# target to generate assembly for a file
src/data/CSVHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C_Structures.dir/build.make CMakeFiles/C_Structures.dir/src/data/CSVHandler.cpp.s
.PHONY : src/data/CSVHandler.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C_Structures.dir/build.make CMakeFiles/C_Structures.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C_Structures.dir/build.make CMakeFiles/C_Structures.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C_Structures.dir/build.make CMakeFiles/C_Structures.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/model/Beam.o: src/model/Beam.cpp.o
.PHONY : src/model/Beam.o

# target to build an object file
src/model/Beam.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C_Structures.dir/build.make CMakeFiles/C_Structures.dir/src/model/Beam.cpp.o
.PHONY : src/model/Beam.cpp.o

src/model/Beam.i: src/model/Beam.cpp.i
.PHONY : src/model/Beam.i

# target to preprocess a source file
src/model/Beam.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C_Structures.dir/build.make CMakeFiles/C_Structures.dir/src/model/Beam.cpp.i
.PHONY : src/model/Beam.cpp.i

src/model/Beam.s: src/model/Beam.cpp.s
.PHONY : src/model/Beam.s

# target to generate assembly for a file
src/model/Beam.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C_Structures.dir/build.make CMakeFiles/C_Structures.dir/src/model/Beam.cpp.s
.PHONY : src/model/Beam.cpp.s

src/model/Node.o: src/model/Node.cpp.o
.PHONY : src/model/Node.o

# target to build an object file
src/model/Node.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C_Structures.dir/build.make CMakeFiles/C_Structures.dir/src/model/Node.cpp.o
.PHONY : src/model/Node.cpp.o

src/model/Node.i: src/model/Node.cpp.i
.PHONY : src/model/Node.i

# target to preprocess a source file
src/model/Node.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C_Structures.dir/build.make CMakeFiles/C_Structures.dir/src/model/Node.cpp.i
.PHONY : src/model/Node.cpp.i

src/model/Node.s: src/model/Node.cpp.s
.PHONY : src/model/Node.s

# target to generate assembly for a file
src/model/Node.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C_Structures.dir/build.make CMakeFiles/C_Structures.dir/src/model/Node.cpp.s
.PHONY : src/model/Node.cpp.s

src/physics/Simulator.o: src/physics/Simulator.cpp.o
.PHONY : src/physics/Simulator.o

# target to build an object file
src/physics/Simulator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C_Structures.dir/build.make CMakeFiles/C_Structures.dir/src/physics/Simulator.cpp.o
.PHONY : src/physics/Simulator.cpp.o

src/physics/Simulator.i: src/physics/Simulator.cpp.i
.PHONY : src/physics/Simulator.i

# target to preprocess a source file
src/physics/Simulator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C_Structures.dir/build.make CMakeFiles/C_Structures.dir/src/physics/Simulator.cpp.i
.PHONY : src/physics/Simulator.cpp.i

src/physics/Simulator.s: src/physics/Simulator.cpp.s
.PHONY : src/physics/Simulator.s

# target to generate assembly for a file
src/physics/Simulator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C_Structures.dir/build.make CMakeFiles/C_Structures.dir/src/physics/Simulator.cpp.s
.PHONY : src/physics/Simulator.cpp.s

src/ui/UIHandler.o: src/ui/UIHandler.cpp.o
.PHONY : src/ui/UIHandler.o

# target to build an object file
src/ui/UIHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C_Structures.dir/build.make CMakeFiles/C_Structures.dir/src/ui/UIHandler.cpp.o
.PHONY : src/ui/UIHandler.cpp.o

src/ui/UIHandler.i: src/ui/UIHandler.cpp.i
.PHONY : src/ui/UIHandler.i

# target to preprocess a source file
src/ui/UIHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C_Structures.dir/build.make CMakeFiles/C_Structures.dir/src/ui/UIHandler.cpp.i
.PHONY : src/ui/UIHandler.cpp.i

src/ui/UIHandler.s: src/ui/UIHandler.cpp.s
.PHONY : src/ui/UIHandler.s

# target to generate assembly for a file
src/ui/UIHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C_Structures.dir/build.make CMakeFiles/C_Structures.dir/src/ui/UIHandler.cpp.s
.PHONY : src/ui/UIHandler.cpp.s

tests/PhysicsTests.o: tests/PhysicsTests.cpp.o
.PHONY : tests/PhysicsTests.o

# target to build an object file
tests/PhysicsTests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/PhysicsTests.cpp.o
.PHONY : tests/PhysicsTests.cpp.o

tests/PhysicsTests.i: tests/PhysicsTests.cpp.i
.PHONY : tests/PhysicsTests.i

# target to preprocess a source file
tests/PhysicsTests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/PhysicsTests.cpp.i
.PHONY : tests/PhysicsTests.cpp.i

tests/PhysicsTests.s: tests/PhysicsTests.cpp.s
.PHONY : tests/PhysicsTests.s

# target to generate assembly for a file
tests/PhysicsTests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/PhysicsTests.cpp.s
.PHONY : tests/PhysicsTests.cpp.s

tests/test_main.o: tests/test_main.cpp.o
.PHONY : tests/test_main.o

# target to build an object file
tests/test_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/test_main.cpp.o
.PHONY : tests/test_main.cpp.o

tests/test_main.i: tests/test_main.cpp.i
.PHONY : tests/test_main.i

# target to preprocess a source file
tests/test_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/test_main.cpp.i
.PHONY : tests/test_main.cpp.i

tests/test_main.s: tests/test_main.cpp.s
.PHONY : tests/test_main.s

# target to generate assembly for a file
tests/test_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/test_main.cpp.s
.PHONY : tests/test_main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... C_Structures"
	@echo "... tests"
	@echo "... src/data/CSVHandler.o"
	@echo "... src/data/CSVHandler.i"
	@echo "... src/data/CSVHandler.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/model/Beam.o"
	@echo "... src/model/Beam.i"
	@echo "... src/model/Beam.s"
	@echo "... src/model/Node.o"
	@echo "... src/model/Node.i"
	@echo "... src/model/Node.s"
	@echo "... src/physics/Simulator.o"
	@echo "... src/physics/Simulator.i"
	@echo "... src/physics/Simulator.s"
	@echo "... src/ui/UIHandler.o"
	@echo "... src/ui/UIHandler.i"
	@echo "... src/ui/UIHandler.s"
	@echo "... tests/PhysicsTests.o"
	@echo "... tests/PhysicsTests.i"
	@echo "... tests/PhysicsTests.s"
	@echo "... tests/test_main.o"
	@echo "... tests/test_main.i"
	@echo "... tests/test_main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

